version: '3'

services:
  crawler:
    build: ./images/crawler
    environment:
      - DEV_MOD=YES
    volumes:
      - ../../:/app
    ports:
      - "3333:3333"
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
